### ISSUE TITLE
New div - reviews

### ISSUE THREAD

**Issue by OZOAR** [OZOAR/CRCExchange#27]
Add new block "reviews" after block "transaction limits".
Text:
Везде лого bitcointalk

РУС:
kirillstoks
Спасибо за быструю сделку.
11 мая 2018, 09:08

MinerAnarchist
Спасибо, отличные ребята, не обманули
10 июля 2018, 14:48

JeyMoon
спасибо ребятам за честную и быструю сделку. респект
16 июля 2018, 11:25

ENG:
kirillstoks
Thank you for a fast transaction.
May 11, 2018, 09:08:06 AM

MinerAnarchist
Thank you guys, all came through smoothly.
July 10, 2018, 02:48:30 PM

JeyMoon
Thanks for an honest and fast transaction, guys!
July 16, 2018, 11:25:31 AM
logo: 

https://www.google.com/search?q=bitcoin+talk+png&tbm=isch&source=univ&client=firefox-b-ab&sa=X&ved=2ahUKEwjF1K7BsafgAhWrhaYKHRYlAUkQsAR6BAgFEAE&biw=1920&bih=966#imgrc=L0JUa8SpCy-1rM:

**Comment by danilchican** [comment]
It's possible to append only after Buy Now section according to design.

**Comment by OZOAR** [comment]
approved
