### ISSUE TITLE
[UI] Display limits near the payment module on the homepage.

### ISSUE THREAD

**Issue by danilchican** [OZOAR/CRCExchange#3]
Display limits near the payment module on the homepage.
See Tasks chapter at Google docs. Point 1.4.

**Comment by danilchican** [comment]
@OZOAR, how does should it look like?

**Comment by OZOAR** [comment]
Under that block
![image](https://user-images.githubusercontent.com/23193846/51175619-e02d3e80-18cb-11e9-96fa-9879ce953895.png)

**Comment by danilchican** [comment]
@OZOAR, OK.
