### ISSUE TITLE
Начальный язык 

### ISSUE THREAD

**Issue by OZOAR** [OZOAR/CRCExchange#34]
Язык сайта должен выбираться соответственно языку браузера/локации. Выбрать более простой вариант

**Comment by danilchican** [comment]
@OZOAR need to use http://lyften.com/projects/laravel-geoip/

**Comment by OZOAR** [comment]
> @OZOAR need to use http://lyften.com/projects/laravel-geoip/

ok. accepted

**Comment by danilchican** [comment]
For geolocation ipgeolocation.io is used.

**Comment by danilchican** [comment]
< 1,5K requests per day are free. If service needs more requests per day than pay new plan.
