### ISSUE TITLE
Изменить блок на "партнёрская программа"

### ISSUE THREAD

**Issue by OZOAR** [OZOAR/CRCExchange#43]
Изменить текст блока "покупка биткойнов при помощи банковской карты" на следующий:

Join our Affiliate Program / Партнерская программа

Place an affiliate link on your website, blog or social media profile. Get 50% of our revenue from every transaction made. / Разместите партнерскую ссылку на свой веб-ресурс и получите 50% нашего дохода от каждой транзакции, совершенной вашими пользователями.

**Кнопка: ** 
Become Affiliate / Стать партнером 

Кнопка ведёт на '/affiliate'

**Comment by OZOAR** [comment]
не сделано

**Comment by danilchican** [comment]
@OZOAR, please clear browser cache.
